<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetIDDetails/GetIDDetails/GetIDDetails" name="GetIDDetails-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GetIDDetails/GetIDDetails/GetIDDetails" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetIDDetails/GetIDDetails/GetIDDetails" location="GetIDDetails.wsdl"/>
  <binding name="GetIDDetails_ptt-binding" type="tns:GetIDDetails_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="GetIDDetails">
      <soap:operation soapAction="GetIDDetails"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="GetIDDetails-service">
    <port name="GetIDDetails-port" binding="tns:GetIDDetails_ptt-binding">
      <soap:address location="jca://eis/ods"/>
    </port>
  </service>
</definitions>